container files/axios/boot
rgreen11/SwitchItProject pull request #2
Opened 2019-05-15 21:59 UTC by vantran23

I create all the container (pages) files and put them in App.js and added the Navbar component.
I installed Axios and Bootstrap.

2019-05-15 23:20 UTC, mikeboyle requested changes
Looks good! One question and a couple of small style nitpicks.

2019-05-15 23:20 UTC, mikeboyle commented on src/App.js
> +        <Route path='/' component={Navbar} />
This is a very small nitpick but I think`<Route />` be indented inside `<HashRouter />`

2019-05-15 23:20 UTC, mikeboyle commented on src/App.js
> +import Calendar from './containers/calendar';
Very tiny nitpick but should these be capitalized like `AddItem` and `MixNMatch` or is there a good reason not to?

2019-05-15 23:20 UTC, mikeboyle commented on src/App.js
> +            <Route path="/additem" exact strict component={addItem} />
Is `/additem` the form for adding a piece of clothing? Will this also still be in a modal?

2019-05-16 14:36 UTC, rgreen11 requested changes
Looks good. Before I merge can you capitalize the names for the files being imported and Wrap the App in a HashRouter

2019-05-18 20:41 UTC, closed without merging